"""empty message

Revision ID: 0a42bdc7903e
Revises: 
Create Date: 2020-09-01 15:02:07.343746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a42bdc7903e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Technology_Master',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('technology_name', sa.String(length=50), nullable=False),
    sa.Column('tech_dependant_tags', sa.String(length=2000), nullable=True),
    sa.Column('stack_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('technology_id')
    )
    op.create_table('App_Tech_Master',
    sa.Column('App_technology_name', sa.String(length=50), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('App_tech_dependant_tags', sa.String(length=2000), nullable=True),
    sa.Column('App_tech_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['Technology_Master.technology_id'], ),
    sa.PrimaryKeyConstraint('App_technology_name')
    )
    op.create_table('Data_Tech_Master',
    sa.Column('Data_technology_name', sa.String(length=50), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('Data_tech_dependant_tags', sa.String(length=2000), nullable=True),
    sa.Column('Data_tech_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['Technology_Master.technology_id'], ),
    sa.PrimaryKeyConstraint('Data_technology_name')
    )
    op.create_table('OS_Tech_Master',
    sa.Column('OS_technology_name', sa.String(length=50), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('OS_tech_dependant_tags', sa.String(length=2000), nullable=True),
    sa.Column('OS_tech_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['Technology_Master.technology_id'], ),
    sa.PrimaryKeyConstraint('OS_technology_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OS_Tech_Master')
    op.drop_table('Data_Tech_Master')
    op.drop_table('App_Tech_Master')
    op.drop_table('Technology_Master')
    # ### end Alembic commands ###
